apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-front
  labels:
    app: finance-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finance-front
  template:
    metadata:
      labels:
        app: finance-front
    spec:
      containers:
        - name: finance-front
          image: ghcr.io/italo-jsm/finance-front:sha-8710878
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: HOSTNAME
              value: "0.0.0.0"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 20
